### ISSUE TITLE
The flows on Homey to the Somfy Tahoma time outHi

### ISSUE THREAD

**Issue by gevoel56** [AdyRock/com.somfy.tahoma#110]
Hi,

I am using Homey and your Somfy TaHoma & connexoon App to manage my 9 window shutters. Since a few months the commands from your app time out and the shutter do not move. The Homey works OK in all other aspects and the phone-app form Somfy works as designed. So I am looking if there is something in between that is not able anymore to connect the two. All things are up to date and have been working fine for years.

Please help.

Gerard van Oel
Almere, The Netherlands

**Comment by JiWo77** [comment]
I have the same problem. If I use the 'test' option for a flow using Somfy Tahoma devices, I reveive a response "Please leave 1 minutes between login attempts."
After two weeks of no connection, suddenly the problem was resolved (around a week ago), but last Friday suddenly the problem appeared again until now. No single response from Homey support, despite sending multiple reminders by e-mail. This is very annoying.
I use the Somfy app with Premium subscription. I live in Utrecht.

**Comment by AdyRock** [comment]
It's not Athom's fault and there's nothing they can do. The problem is down to Somfy's security method.
I keep trying to add measures to resolve the problem but the Homey clients are not able to synchronise with each other.

**Comment by gevoel56** [comment]
Hi Adrian,

Glad to get a response, thank you. If the problem is not coming from Atoms side end you know it and keep on trying to resolve it, then all U can do is sit and wait until there is some movement from Somfy’s side. Until them I have a very basic “program” running on the Tahama which keeps the house cool, but i’d ;ove to use the Homey again as the rpogramming possibilities there are a lot better. Well, we will see.

Ik something changes for the better, can you keep me posted? Tia.

Regards,

Gerard van Oel
Almere

--

**Comment by JiWo77** [comment]
Dear Adrian,
Thank you for your response. It is very nice to at least having received some information about the issue.
Do you know whether Somfy is known with this problem between Homey and Somfy, and whether they are working on a solution?
Kind regards.

**Comment by AdyRock** [comment]
Somfy won't change anything as it's their security policy to prevent brute force attacks on users passwords.
I have to find a way to prevent Homey clients, that know nothing about each other, to distribute their login attempts, so that they don't hit the Somfy servers at the same time.

**Comment by JiWo77** [comment]
Dear Adrian,
Thank you for your clarification. This leads to a couple of questions and possible solutions for the short term.

1) I have pre-ordered the new Homey Pro 2023, which would be delivered within a week or so. Do you know this problem would also be persistent with the new Homey pro? Or would the Homey pro use other connections that will not lead to this error?

If the new Homey pro will not be a solution for me:
2) Do you mean, the problem will only occur when my flows are contacting Somfy multiple times per minute?

I guess I have ca 25 flows that use Somfy for input or output. I have a Somfy sun sensor and 7 Somfy screens that react on sun, time of day, temperature, etc. The strange thing is I had this problem continuously for two weeks, and then 3 days continuously without any problem (last Tuesday until Friday), and then the problem came back, again continuously. Therefore, I would be surprised when a solution would be that my flows don't contact Somfy multiple times per minute.
I think I have also seen earlier, error messages saying that Somfy doubles the waiting period until it allows a new login attempt. 
3) Maybe this long waiting period could be the cause of the long periods that Somfy doesn't respond to requests?

4) Would it be a solution to switch off my flows that contact Somfy for a period (how long?), to stop the overload of login attempts? 

5) In the meantime, I could change flows that are triggered by sun intensity (changes every minute) into flows triggered by e.g. changing temperature (not Somfy). Do you think that would help?

Thank you very much if you could reply to me.

**Comment by AdyRock** [comment]
Homey Pro doesn't have the problem because each one comes from your unique IP address.
The problem with Homey is all the clients are hosted on a few servers. That means multiple Somfy users will have the same IP address and therefore it looks like a brute force attack on passwords, if there is an issue that causes them to all try and log in at the same time. I believe (but have no evidence) that the recent Homey server issue meant that all the clients came back online at the same time, so they all tried to login at the same time and that is what triggered this outage. 
Once an IP address is blocked, the only way to clear it is to not use it for 15 minutes. On Homey Pro that is easy to manage, but with several thousand Homey clients that can't coordinate with each other, that is a challenge. 
So, it's not the accesses of logged in clients that is a problem, it is just getting them logged in to start with. On top of that, each login is only valid for about an hour and then needs to be refreshed. 

As an analogy, imagine cars on a ring road with no exits. All the cars go round and round without any problems until there's a crash. Now all the cars behind the crash just keep piling into the crash so it can't be cleared. All the cars in front of the crash are totally unaware of the problem and keep going, until they eventually catch up to the end of the crash and pile in as well. Just to make matters worse, every driver is blind so they can't see the impending crash in front of them and have no way to avoid being involved in the crash. Once every car on the ring road has hit the crash, then it's safe to start clearing the problem so everyone is on their way again. Not sure if that helps 😁

**Comment by gevoel56** [comment]
Hi Adrian,This is clear . Thank you. But…(There is always a but) is this causing my 30000 ms time out as well?RegardsGerard.Verstuurd vanaf mijn iPhoneOp 19 jun. 2023 om 16:35 heeft Adrian Rockall ***@***.***> het volgende geschreven:﻿
Homey Pro doesn't have the problem because each one comes from your unique IP address.
The problem with Homey is all the clients are hosted on a few servers. That means multiple Somfy users will have the same IP address and therefore it looks like a brute force attack on passwords, if there is an issue that causes them to all try and log in at the same time. I believe (but have no evidence) that the recent Homey server issue meant that all the clients came back online at the same time, so they all tried to login at the same time and that is what triggered this outage.
Once an IP address is blocked, the only way to clear it is to not use it for 15 minutes. On Homey Pro that is easy to manage, but with several thousand Homey clients that can't coordinate with each other, that is a challenge.
So, it's not the accesses of logged in clients that is a problem, it is just getting them logged in to start with. On top of that, each login is only valid for about an hour and then needs to be refreshed.
As an analogy, imagine cars on a ring road with no exits. All the cars go round and round without any problems until there's a crash. Now all the cars behind the crash just keep piling into the crash so it can't be cleared. All the cars in front of the crash are totally unaware of the problem and keep going, until they eventually catch up to the end of the crash and pile in as well. Just to make matters worse, every driver is blind so they can't see the impending crash in front of them and have no way to avoid being involved in the crash. Once every car on the ring road has hit the crash, then it's safe to start clearing the problem so everyone is on their way again. Not sure if that helps 😁

**Comment by AdyRock** [comment]
Yes, that's what causes the timeout. Each time you try to send a command, the app will attempt to login and send it. As the login fails it will retry a couple of times and eventually timeout.

**Comment by gevoel56** [comment]
OK, so now I have to convince my wife we really need the new Homey. ;-)Thanks for the info.Gerard.Verstuurd vanaf mijn iPhoneOp 19 jun. 2023 om 17:49 heeft Adrian Rockall ***@***.***> het volgende geschreven:﻿
Yes, that's what causes the timeout. Each time you try to send a command, the app will attempt to login and send it. As the login fails it will retry a couple of times and eventually timeout.

**Comment by gevoel56** [comment]
What I hadn’t realized is that the communication went through servers. I was under the impression that my private Homey connected with my private Tahoma. But My Homey connects to the Homey server which communicates to the Somfy server which talks to my private Tahoma? Wow. Or am I completely amiss now? I know next to nothing about networking and so. Computers are ok.Gerard.Verstuurd vanaf mijn iPhoneOp 19 jun. 2023 om 17:55 heeft ***@***.*** het volgende geschreven:﻿OK, so now I have to convince my wife we really need the new Homey. ;-)Thanks for the info.Gerard.Verstuurd vanaf mijn iPhoneOp 19 jun. 2023 om 17:49 heeft Adrian Rockall ***@***.***> het volgende geschreven:﻿
Yes, that's what causes the timeout. Each time you try to send a command, the app will attempt to login and send it. As the login fails it will retry a couple of times and eventually timeout.

**Comment by AdyRock** [comment]
I might be getting confused with the people posting here.
If you have a Homey Pro then it will connect directly to the Somfy server. If you have enabled developer mode in your Somfy account then just the login is via their servers and control will be between your Homey Pro and your Tahoma bridge. 

If are using Homey (cloud) then Homey will make all communication directly with Somfy servers and they will communicate with your Tahoma. 

I hope that makes sense.

**Comment by gevoel56** [comment]
You’re douing fine. Thanks for the explanation.Verstuurd vanaf mijn iPhoneOp 19 jun. 2023 om 19:59 heeft Adrian Rockall ***@***.***> het volgende geschreven:﻿
I might be getting confused with the people posting here.
If you have a Homey Pro then it will connect directly to the Somfy server. If you have enabled developer mode in your Somfy account then just the login is via their servers and control will be between your Homey Pro and your Tahoma bridge.
If are using Homey (cloud) then Homey will make all communication directly with Somfy servers and they will communicate with your Tahoma.
I hope that makes sense.

**Comment by JiWo77** [comment]
Hi Adrian, also from me many thanks for your explanations. I just received an e-mail that my Homey pro order of mid April will hopefully be delivered in July (via Robbshop.nl), so it is a pity I will have to wait for some more weeks. But it helps I at least understand the problem and why it is difficult to solve in the short term.

**Comment by JiWo77** [comment]
Dear all, the contact between Somfy devices and Homey premium has been restored in my home since today (5:19 am)! I could see this from my Somfy sun sensor which provides data every minute.
I assume no structural solution, but only due to all 'cars have hit the crash location', Adrian?
The last time, about two weeks ago, the period the connection was working lasted for about three days...

**Comment by AdyRock** [comment]
It could be that the block was removed or your Homey migrated to a different server. Either way, glad it's working again.
