### ISSUE TITLE
cannot install IO screen

### ISSUE THREAD

**Issue by rpkbs** [AdyRock/com.somfy.tahoma#30]
trying to add a IO screen on homey app.

pressing install 
Inloggen niet gelukt. Ga a.u.b. naar het instellingen scherm en geef Homey toegang tot TaHoma.
Login failed. Please go to the settings screen and give Homey access to TaHoma.

How to solve this?
or is there a manual to install a IO screen with this app?

gr
Robin

**Comment by AdyRock** [comment]
Have you entered the Tahoma username and password in the Configure App screen and tapped on Save credentials prior to adding any devices?

**Comment by rpkbs** [comment]
Thanks for replying.

What do you mean by configure app screen? Where is that?
I have a connexoon account. And now use Somfy connexoon window app on my phone.



Van: Adrian Rockall ***@***.***>
Verzonden: vrijdag 2 juli 2021 11:33
Aan: AdyRock/com.somfy.tahoma ***@***.***>
CC: rpkbs ***@***.***>; Author ***@***.***>
Onderwerp: Re: [AdyRock/com.somfy.tahoma] cannot install IO screen (#30)


Have you entered the Tahoma username and password in the Configure App screen and tapped on Save credentials prior to adding any devices?

**Comment by rpkbs** [comment]
Found it…..thanks…..it works,,,….

Can you also set the My position with the app?



Van: Adrian Rockall ***@***.***>
Verzonden: vrijdag 2 juli 2021 11:33
Aan: AdyRock/com.somfy.tahoma ***@***.***>
CC: rpkbs ***@***.***>; Author ***@***.***>
Onderwerp: Re: [AdyRock/com.somfy.tahoma] cannot install IO screen (#30)


Have you entered the Tahoma username and password in the Configure App screen and tapped on Save credentials prior to adding any devices?

**Comment by AdyRock** [comment]
It's not currently possible via the app but it looks like it is possible some devices, so I could possibly add that.
I think I would make it an advanced setting rather than a capability in the normal place as it is not something I would envisage changing very often, so no point cluttering the interface.
If it is something you would like then send me the Device log from the Configure App screen and i will see if the command is available for your screen.
