### ISSUE TITLE
No more connection with somfy IO devices

### ISSUE THREAD

**Issue by keitje** [AdyRock/com.somfy.tahoma#54]
Hello AdyRock,

Homey support send me to you. I am using the test version of the Somfy Tahoma & Connexoon app fine for months with my screens. But suddenly the Somfy app in the Homey app is not working anymore and I cannot add new devices. I removed the existing devices, now I have no devices anymore. Also tried to reinstall the app on the Homey Bridge but I get an error when I use the Homey App store. I think because the app is already installed. The mail that I send is attached and also the error when I try te reinstall the test version.
Homey support says, sorry cant help you talk to the developer.
Do you know what is happening? regards, Michael
![problems with homey](https://user-images.githubusercontent.com/45143839/153244702-2b381c47-4ee8-4d69-ab44-456e54a4d97c.JPG)

**Comment by AdyRock** [comment]
Hi, there is a known issue with the store that is preventing the app from being installed. I have been informed that the issue has been located, and a solution is in the pipeline. 

As for the initial problem, that is also a known issue because Somfy blocks access due to many requests coming from the same IP address. When the app is running on Homey, many users share the same IP address as each Homey is a virtual instance. I have contacted Somfy about this, but they say there is nothing they can do.
I have added more conditions to the latest version in order to reduce the problem, but this issue is why I haven't submitted the app to be officially released. 

The app works fine on the Homey Pro because each user has a unique IP address.

Sorry I can't be more helpful, but I am doing my best to resolve this.

**Comment by AdyRock** [comment]
This should all be OK now!

**Comment by keitje** [comment]
> This should all be OK now!

Thanks for your help!

**Comment by AdyRock** [comment]
I will close this issue but please let me know if there are still problems.
